version: '3.8'

services:
  demo:
    build: ./demo
    container_name: demo_service
    ports:
      - "9090:9090"
    volumes:
      - ./uploads:/app/uploads
    restart: always
    networks:
      - backend

  binaryzacja:
    build: ./binaryzacja
    container_name: binaryzacja_service
    ports:
      - "9998:9998"
    restart: always
    networks:
      - backend
